server:
  port: 63110

spring:
  mvc:
    #knife4j配置
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: content-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_edu_content?serverTimezone=UTC&userUnicode=true&useSSL=false
    username: root
    password: 20010825

#mybatis-plus配置
mybatis-plus:
  type-aliases-package: com.onlineedu.content.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
